// Generated by scripts/generate-engine-pins.mjs from llama.cpp b11166. Do not edit.
import type { EngineBuilds, EngineRelease } from "./pins.ts";

export const ENGINE_RELEASE: EngineRelease = {
	name: "llama.cpp",
	release: "b11166",
	commit: "a72e04abe0fe9b36e203033ac71bd5f379c35bc5",
};

export const ENGINE_BUILDS: EngineBuilds = {
	"win32-x64": {
		cpu: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-cpu-x64.zip",
				sizeBytes: 18567816,
				sha256: "a9372816f6cff6a6f16ebdc22e9fdcd6da6ab42838bc5c082a0c6ad92633f84a",
			},
		],
		vulkan: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-vulkan-x64.zip",
				sizeBytes: 32456823,
				sha256: "632bc0e6e1d62fd324fa05119ba2f0938e7a8fcf58472e1d566a4baf76ee2866",
			},
		],
		"cuda-12": [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-cuda-12.4-x64.zip",
				sizeBytes: 254719578,
				sha256: "c86bcd5bf2646a6ab3527186baa2ecf0b1a8aa19313d644be082c1d74960e7c8",
			},
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/cudart-llama-bin-win-cuda-12.4-x64.zip",
				sizeBytes: 391443627,
				sha256: "8c79a9b226de4b3cacfd1f83d24f962d0773be79f1e7b75c6af4ded7e32ae1d6",
			},
		],
		"cuda-13": [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-cuda-13.4-x64.zip",
				sizeBytes: 150242304,
				sha256: "e37b9e753a9c00c9836ca2b6d77357db9ea2510e0b675cb3c4f2a1514b8a627a",
			},
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/cudart-llama-bin-win-cuda-13.4-x64.zip",
				sizeBytes: 423535356,
				sha256: "738f8c251ac22b70c3ae6f83a10cf222725df0395246a2cf58f32bdb85fbe668",
			},
		],
		rocm: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-rocm-10.0-x64.zip",
				sizeBytes: 252638629,
				sha256: "74e9908a35020735e925c4266c2c481b9c46e9faf57f2fd7920493931e5b6791",
			},
		],
		sycl: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-sycl-x64.zip",
				sizeBytes: 120202410,
				sha256: "f0f12697a8e6db808627d879834f6dd1f00f9c2d499964aca5363a5f5e4d3296",
			},
		],
		openvino: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-openvino-2026.4-x64.zip",
				sizeBytes: 88303236,
				sha256: "e134205b83fd5f6918656faae646e77116cfe794af5432a0b476c1b44e5e9d21",
			},
		],
	},
	"win32-arm64": {
		cpu: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-cpu-arm64.zip",
				sizeBytes: 12040752,
				sha256: "5ad47708c8eb5801d860c14872d2cb69a987050dc064c3fa63d2afa7c9dfed1b",
			},
		],
		"cuda-13": [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-cuda-13.4-arm64.zip",
				sizeBytes: 143079524,
				sha256: "1343324554266dda97dd0e4b82a7b19428c0b9fd30382cd5b813af6374ad0d4d",
			},
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/cudart-llama-bin-win-cuda-13.4-arm64.zip",
				sizeBytes: 153262407,
				sha256: "642dcde8805b3e3165ca710a5443b3b4044b27d96bd3ee3132473988c9bcb774",
			},
		],
		opencl: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-win-opencl-adreno-arm64.zip",
				sizeBytes: 12855761,
				sha256: "b79fc09895bd7e6ebf22526d9b3a87d48ce739e1cadcfb5344108f22938f6e9d",
			},
		],
	},
	"linux-x64": {
		cpu: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-x64.tar.gz",
				sizeBytes: 17013191,
				sha256: "79dccaacf907665a278a9507f583027c294c97f0e93f372364086d9a246e38a5",
			},
		],
		vulkan: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-vulkan-x64.tar.gz",
				sizeBytes: 30957327,
				sha256: "69e26c5e577e1c17dec0b59d3146f008424297a2c64a92fa445365e264585667",
			},
		],
		"cuda-12": [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-cuda-12.8-x64.tar.gz",
				sizeBytes: 169507048,
				sha256: "cb677c03518acac2799864fc1c934c1006b8eb54e5a33ffecd97374920807f8c",
			},
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/cudart-llama-b11166-bin-ubuntu-cuda-12.8-x64.tar.gz",
				sizeBytes: 594377709,
				sha256: "952c2cb2a040cb8a956bf15168b2e31772641f7e5745497a559fb88083c26c83",
			},
		],
		"cuda-13": [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-cuda-13.4-x64.tar.gz",
				sizeBytes: 149754289,
				sha256: "326a58580a51b39a6e9f18ce29972ec078242f64d7869255cb513c96fd34da1b",
			},
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/cudart-llama-b11166-bin-ubuntu-cuda-13.4-x64.tar.gz",
				sizeBytes: 440236536,
				sha256: "7f8e0553b224d804c494c71dc21adff0744ef91d5769ac7c2dc71b2770d5c16e",
			},
		],
		rocm: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-rocm-10.0-x64.tar.gz",
				sizeBytes: 235512822,
				sha256: "e347d6bbd03efdf8c55e55e95be9cc2576c99110fd604aab555e90b16bde90c7",
			},
		],
		sycl: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-sycl-fp32-x64.tar.gz",
				sizeBytes: 55004428,
				sha256: "c3fec2e1b65c630e34810d29b2c3e6a5681bf458949ad75d5de9f7e4f49313da",
			},
		],
		openvino: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-openvino-2026.4-x64.tar.gz",
				sizeBytes: 109083751,
				sha256: "6544e962b37b9e1c43d9f14414040004ad5eac8820e3409a6d44a87c43718204",
			},
		],
	},
	"linux-arm64": {
		cpu: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-arm64.tar.gz",
				sizeBytes: 13604555,
				sha256: "d0c46f92c41a53b168132a1e7fd01b23895bb6e4c4ae4c95cc511edb0ca0e239",
			},
		],
		vulkan: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-vulkan-arm64.tar.gz",
				sizeBytes: 24775205,
				sha256: "7e75a99b8291b1e955a0cb8afc1a591abb5394dbca2b893f0f6d81c047b75a60",
			},
		],
		"cuda-13": [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-ubuntu-cuda-13.4-arm64.tar.gz",
				sizeBytes: 145519137,
				sha256: "a9627a71aa50b664370d05f01b03d254a8dd78a1dce62789c5b1e7a230e2ec6a",
			},
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/cudart-llama-b11166-bin-ubuntu-cuda-13.4-arm64.tar.gz",
				sizeBytes: 552522326,
				sha256: "e63b4c2cf014926827da9c1e431a02085526586d5ac4ba50cd11fc3fc7f844d0",
			},
		],
		hexagon: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-linux-arm64-snapdragon.tar.gz",
				sizeBytes: 18858843,
				sha256: "6f8faca741eb7e51ab04d0f89298a7e5bd69fa3c0798a246e27446cfd8be6088",
			},
		],
	},
	"darwin-x64": {
		cpu: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-macos-x64.tar.gz",
				sizeBytes: 11243593,
				sha256: "6f6793076363d798378ca32ea1e726be2cf81b3df45f49ce345289ff668aaa3b",
			},
		],
	},
	"darwin-arm64": {
		metal: [
			{
				url: "https://github.com/ggml-org/llama.cpp/releases/download/b11166/llama-b11166-bin-macos-arm64.tar.gz",
				sizeBytes: 11202588,
				sha256: "90ecd5ee881569ab090d3c1b7249b597ba505d1d2db57d61df15894dcf77a0a2",
			},
		],
	},
};
